apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-clusters-job
  namespace: stonesoup
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: shebert
          containers:
            - name: delete-clusters
              image: quay.io/scoheb/cluster-utils:f1caab9006ad328a941b8a6460c66e4cdcaefc9f0b64e8d4328ada33a890b407
              envFrom:
                - secretRef:
                    name: aws-credentials
                - secretRef:
                    name: oc-credentials
                - secretRef:
                    name: slack-bot-credentials
          restartPolicy: Never
